config/routes.rb
QLink::Application.routes.draw do

get '/404', to: 'errors#not_found'
get '/500', to: 'errors#server_error'

resources :events do
   member do
   end
   collection do
     post 'save_event'
     get 'index'
     get 'showcalender'
     get 'firstpage'
     get 'invitepeople'
     post 'save_eventemail'
     get 'firstpageremove'
     get 'update_event'
     post 'updatesave_event'
   end
  end
  
resources :profiles do
  member do
  end
  collection do

    get 'profile_form'
    post 'create'
    get 'about'
    get 'events'
    get 'search'
    post 'fill_details'
    post 'add_picture'
    get 'upload_file_for_postmessage'
    get 'photos'
    get 'videos'
    get 'change_profile_pic'  
    post 'save_profile'
    get 'my_posts'
    get 'my_blogs'
    get 'my_discussions'
  end
end
resources :home do
  member do
  end
  collection do
    get 'home'
    post 'create'
    post 'postmessage'
    get 'upload'
    get 'latest_blogs'
    get 'latest_discussions'
    get 'latest_events'
    get 'destroy'
    get 'kudos_to_post'
  end
end

    
match "/contacts/:gmail/callback" => "contacts#contacts_callback"
match "/contacts/failure" => "contacts#failure"
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "sessions"}
root :to => "users#index"
resources :users do
    member do

    end
    collection do
        post 'reset_password'
        get 'welcomepage'  
        get 'skip_import_contacts' 
        get 'skip_add_profile_picture'
        get 'set_password'
        post 'save_password'         
    end
end

resources :discussions do   
  member do
  
  end
  collection do
    get 'view_disc'
   post 'create'
   get 'my_disc'
   get 'top_disc'
   get 'latest_disc'
   get 'add_kudos_discussion'
   get 'list_by_tags'
   get 'destroy'
   get 'kudos_to_discussion'
  end
end

resources :blogs do   
  member do
  
  end
  collection do

    get'add_kudos_blog'
    get 'view_blog'
    post 'create'
    get 'my_blog'
    get 'top_blog'
    get 'latest_blog'
    get 'list_by_tags'
    get 'destroy'
    get 'kudos_to_blog'
  end
end

resources :answers  do
  member do
  end
  collection do
    post 'create_ans'
    get 'add_kudos_answer'
    get 'kudos_to_answer'
  end
end

resources :comments  do
  member do
  end
  collection do
    get 'add_kudos_comments'
    post 'create_comment'
     get 'kudos_to_comment'
  end
end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :discussion_id ,:user_id

  has_one :user
  belongs_to :discussion

end

app/models/blog.rb
class Blog < ActiveRecord::Base



  attr_accessible :content, :tag, :title, :user_id, :image, :remote_image_url
  validates_presence_of :title
  has_one :user
  mount_uploader :image, ImageUploader
  has_many :comments

end

app/models/blog_tags.rb
class BlogTags < ActiveRecord::Base
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 attr_accessible :content, :blog_id ,:user_id

  has_one :user
  belongs_to :blog
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name, :user_id
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  attr_accessible :content, :title, :tag, :user_id
  has_one :user
  has_many :answers

end

app/models/discussion_tags.rb
class DiscussionTags < ActiveRecord::Base
  attr_accessible :name
end

app/models/event.rb
class Event < ActiveRecord::Base



  attr_accessible :allday, :description, :endtime, :start, :title, :user_id,:eventId,:flag

  validates_presence_of :title
  validate :validate_end_date_before_start_date
  has_one :user
  
  def validate_end_date_before_start_date
    if endtime && start && endtime < start
      errors.add(:endtime,"")
    end
  end


end

app/models/eventemail.rb
class Eventemail < ActiveRecord::Base
  attr_accessible :email, :event_id
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i,:message => "invalid email"
end

app/models/kudos_to_answer.rb
class KudosToAnswer < ActiveRecord::Base
 attr_accessible :user_id,:answer_id
end

app/models/kudos_to_blog.rb
class KudosToBlog < ActiveRecord::Base
   attr_accessible :user_id,:blog_id
end

app/models/kudos_to_posts.rb
class KudosToPosts < ActiveRecord::Base
  attr_accessible :kudos, :user_id, :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :description, :user_id, :image, :receiver_id, :video, :kudos
  has_one :user
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  attr_accessible :date_of_birth, :first_name, :last_name, :place, :user_id, :image, :gender
  has_one :user
   mount_uploader :image, ImageUploader

 validates_presence_of :date_of_birth, :first_name, :last_name, :place, :gender

 # searchable do
 #    text :first_name, :last_name
 #  end
end

app/models/user.rb
class User < ActiveRecord::Base

  	# Include default devise modules. Others available are:
  	# :token_authenticatable, :confirmable,
  	# :lockable, :timeoutable and :omniauthable

  	devise :database_authenticatable, :registerable, :token_authenticatable,
        :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  	# Setup accessible (or protected) attributes for your model

  	attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :passwordflag,:token,:refresh_token
    
    
    
  	# attr_accessible :title, :body

has_many :post   
has_many :event
has_many :blog
has_many :discussion
has_one :profile



  	def self.find_for_google_oauth2(access_token, signed_in_resource=nil)

		    data = access_token['info']
		    if user = User.where(:email => data['email']).first
			     return user
		    else #create a user with stub pwd
			     User.create!(:email => data['email'], :password => Devise.friendly_token[0,20],  :passwordflag => :false)

		    end
	  end

    def self.create_password(password)
        if password.present?
           encrypted_password = Digest::SHA512.hexdigest(password)
        end
        return encrypted_password
    end
end

app/models/userevent.rb
class Userevent < ActiveRecord::Base

  attr_accessible :description, :endtime, :start, :title, :user_id, :eventid

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_filter :authorize_user!

	def create 
  params[:blog][:user_id]=current_user.id
 # params[:blog][:tag].gsub(/\'/, '')
  @blog_create = Blog.new(params[:blog])
  if @blog_create.save
               flash[:notice] = "Blog Posted"
  else
     flash[:alert] = "Blog not Posted"           
    end  
    redirect_to  top_blog_blogs_path  
  end

  def my_blog
    @guestuserid=current_user.id
    @blogs_all = Blog.find_by_sql("select * from blogs where user_id=#{@guestuserid} limit 5;")
  end	

  def latest_blog

    @blogs_all = Blog.find_by_sql("select * from blogs order by id DESC limit 3;")
  end 
  
  def top_blog

    @blogs_all = Blog.find_by_sql("select * from blogs order by kudos DESC limit 3;")
  end 

  def view_blog
   @blog_view = Blog.find(params[:id])  
   @comments = @blog_view.comments
   @comment_count = Comment.where(:blog_id => params[:id]).count 
  end

  def add_kudos_blog
  @add = Blog.find(params[:id])
  @add.update_attribute("kudos", @add.kudos + 1)
  redirect_to  :controller=>"blogs", :action=>"view_blog", :id=>params[:id]
 end
 
 def list_by_tags
       tag = params[:tag]
       @blogs_all = Blog.find_by_sql("select * from blogs where tag = '#{params[:tag]}' limit 5;")

          
end


def destroy
    @delete_blog = Blog.find(params[:id])
      @delete_blog.destroy
      respond_to do |format|
          format.js
          format.html { redirect_to  top_blog_blogs_path }    
    end
  end

def kudos_to_blog
    post_id=params[:id]
    @post=Blog.find(post_id)
    if @post.kudos.nil?
      @post.kudos=1
    else
      @post.kudos=@post.kudos + 1
    end
    @post.update_attribute("kudos", @post.kudos)
    KudosToBlog.create(:user_id=>current_user.id, :blog_id=>post_id)
    redirect_to  :controller=>"blogs", :action=>"view_blog", :id=>params[:id]
  end
end

 

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def resource_name
   		:user
  	end

 	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
  	def resource_class
  		devise_mapping.to
	end
end

app/views/blogs/create.html.erb
Posted

app/views/blogs/form_blog.html.erb
 <link href="/assets/blogs.css" media="screen" rel="stylesheet" type="text/css" />
 
    <div id="form_box">
    <h4 style="margin-left: 200px;">New Blog</h4>

     
      <fieldset style="margin-left: 200px;margin-top: 20px;">  
      <%= form_for :blog, :url => {:controller => 'blogs', :action => 'create'} do |f| %>

      <div class="control-group">
         <%=f.label :blog_header ,:class=>"control-label" %>
         <div class="controls">
         <%=f.text_field :title ,:autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
        </div>
      </div>
      
      <div class="control-group">
         <%=f.label :content , :class=>"control-label"%>
         <div class="controls">
         <%=f.text_area :content, :rows => 4, :cols => 30 ,:id=>"textarea", :class => 'option-large'%>
         </div>
      </div>

      
      <p> <%= f.file_field :image %></p>
      
      <p> Or image URL<%= f.text_field :remote_image_url %> </p>
      <div class="control-group">
         <%=f.label :tag ,:class=>"control-label" %>
         <div class="controls">
         <%= f.select(:tag, ['Phone', 'Email','Website','Address', 'Occupation'], {},  :id=>"multiple",:class=>"select2", :multiple=>"multiple" ,:style=>"width:200px" ) %>
        </div>
      </div>
        
        
      <%= f.submit "Post", 'class'=>"btn btn-primary"%> 

      <% end %>
    
</div>
<script>
  $('.select2').select2({ placeholder : '' });
</script>
<% if @blogs_all.empty?%>
<%else%>

<div id ="Question">
<div class = "well">
    <%@blogs_all.reverse_each  do |blog| %>
            <% user=Profile.find_by_user_id(blog.user_id)%>


            <h4><strong><h1 style="padding-left: 20px;"> <%= link_to blog.title, {:controller => "blogs", :action => "view_blog", :id => blog.id }%></h1></a></strong></h4>
            
          <% if blog.image_url.nil?%>
          <%else%> 
          <div class="span2">

          <a href="#" class="thumbnail">
           <%= image_tag blog.image_url().to_s if blog.image?  %>
          </a>
        </div>

          <% end%>

            <div class="span6">      


                <p style="padding-left: 20px;"><%= blog.content %></p>

            </div>
            
                    <br> <br> <br> 
                    <p><% if user.image_url.nil?%>
                        <i class="icon-user"></i>
                        <% else%><%= image_tag user.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:45px;height:45px;"%>
                        <% end%>&nbsp<%= link_to "#{user.first_name}", {:controller => "profiles", :action => "about", :id => blog.user_id }%>&nbsp </td>
                   | <i class="icon-calendar"></i> Posted <%= Time.at(blog.created_at) %>
                   | <i class="icon-share"></i> <%= blog.kudos%> Kudos
                   | <i class="icon-tags"></i> Tags : <a href=""><span class="label label-info"> <%=blog.tag %> </span></a> 
             </p>

    <%end%>  
      
</div>

</div>



<% end%>

app/views/blogs/latest_blog.html.erb
 
 <link href="/assets/blogs.css" media="screen" rel="stylesheet" type="text/css" />
 <script src="js/jquery-1.9.1.min.js"></script>
 <script src="js/select2.min.js"></script>
 <link rel="stylesheet" type="text/css" href="css/select2.css"/> 
 <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/> 
 <link rel="stylesheet" type="text/css" href="../select2-bootstrap.css"/>

    <div id="form_box">
    <h4 style="margin-left: 200px;">New Blog</h4>

     
      <fieldset style="margin-left: 200px;margin-top: 20px;">  
      <%= form_for :blog, :url => {:controller => 'blogs', :action => 'create'} do |f| %>

      <div class="control-group">
         <%=f.label :blog_header ,:class=>"control-label" %>
         <div class="controls">
         <%=f.text_field :title ,:autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
        </div>
      </div>
      
      <div class="control-group">
         <%=f.label :content , :class=>"control-label"%>
         <div class="controls">
         <%=f.text_area :content, :rows => 4, :cols => 30 ,:id=>"textarea", :class=>"input-xlarge"%>
         </div>
      </div>
      
       
    <div class="control-group">
    <%=f.label :Image , :class=>"control-label"%>
   
              <div class="controls"> 
                <%= f.file_field :image ,:class=>"control-label", :id=>"textinput", :class=>"input-xlarge" %>
              </div>
   
      </div>
      <div class="control-group">
         <%=f.label :tag ,:class=>"control-label" %>
         <div class="controls">
         <%= f.select(:tag, ['Personal', 'Tech','News', 'Occupation'],:id=>"multiple",:class=>"select2", :multiple=>"multiple" ,:style=>"width:200px" ) %>
        </div>
      </div>
        
      <%= f.submit "Post", 'class'=>"btn btn-primary"%> 

      <% end %>
    
</div>
<script>
  $('.select2').select2({ placeholder : '' });
</script>

<% if @blogs_all.empty?%>
<%else%>
<div id ="Question">

<div class="span12">  
    <ul class="nav nav-tabs" >
         
          <li style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Top Blogs', top_blog_blogs_path%></li>
         <li  class="active"  style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Latest Blogs', latest_blog_blogs_path%></li>
         <li   style="width: 266px; text-align: center;font-size:15px;"><%= link_to 'My Blogs',  my_blog_blogs_path%></li>  
    </ul>   
</div>

<br><br><br>

    <%@blogs_all.each  do |blog| %>
    <div style =" border:2px solid #e3e3e3;">
            <% user=Profile.find_by_user_id(blog.user_id)%>
            <h4 style = "margin-left:20px;margin-right:20px;"><strong><h4> <%= link_to blog.title, {:controller => "blogs", :action => "view_blog", :id => blog.id }%></h4></strong></h4>
            <div style="float: right;font-size: 9pt;color:#4682B4;margin-right:20px;margin-top:-30px;"><i class="icon-calendar"></i> Posted <%= blog.created_at.to_date.strftime("%B %d, %Y") %></div>
          <% if blog.image_url.nil?%>
          <%else%> 
          <div class="span2">
            <a href="#" class="thumbnail">
            <%= image_tag blog.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:100px;height:50px;" if blog.image?  %>
            </a>
          </div>
        </br></br></br></br>
          <% end%>
        
            <p style = "margin-left:20px;margin-right:20px;font-size:11pt;"><%= blog.content %> </p> 
            <div class= "well" style = "margin-top:20px;margin-left:20px;margin-right:20px;height:20px;">
          <div style = "height:20px;font-size:10px;color:#4682B4;margin-left:-12px;">
                    <% if user.image_url.nil?%>
                       <img src="http://critterapp.pagodabox.com/img/user.jpg" style="margin-right: 10px; width:45px;height:45px;">
                        <% else%> <div style="margin-top:-12px;float:left;">
                          <%= image_tag user.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:45px;height:45px;"%>
                        </div>
                        <% end%><%= link_to "#{user.first_name}", {:controller => "profiles", :action => "about", :id => blog.user_id }%> 
                   | <i class="icon-share"></i> <%= blog.kudos%> Kudos
                   | <i class="icon-tags"></i> Tags : <%= link_to blog.tag, {:controller => "blogs", :action => "list_by_tags", :tag => blog.tag } , :class => "label label-info" %> 
       </div>             
    </div>
    </div></br>     
    <%end%>  

</div>

<% end%>

app/views/blogs/my_blog.html.erb
 
 <link href="/assets/blogs.css" media="screen" rel="stylesheet" type="text/css" />
 <script src="js/jquery-1.9.1.min.js"></script>
 <script src="js/select2.min.js"></script>
 <link rel="stylesheet" type="text/css" href="css/select2.css"/> 
 <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/> 
 <link rel="stylesheet" type="text/css" href="../select2-bootstrap.css"/>

    <div id="form_box">
    <h4 style="margin-left: 200px;">New Blog</h4>

     
      <fieldset style="margin-left: 200px;margin-top: 20px;">  
      <%= form_for :blog, :url => {:controller => 'blogs', :action => 'create'} do |f| %>

      <div class="control-group">
         <%=f.label :blog_header ,:class=>"control-label" %>
         <div class="controls">
         <%=f.text_field :title ,:autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
        </div>
      </div>
      
      <div class="control-group">
         <%=f.label :content , :class=>"control-label"%>
         <div class="controls">
         <%=f.text_area :content, :rows => 4, :cols => 30 ,:id=>"textarea", :class=>"input-xlarge"%>
         </div>
      </div>
      
       
    <div class="control-group">
    <%=f.label :Image , :class=>"control-label"%>
   
              <div class="controls"> 
                <%= f.file_field :image ,:class=>"control-label", :id=>"textinput", :class=>"input-xlarge" %>
              </div>
   
      </div>
      <div class="control-group">
         <%=f.label :tag ,:class=>"control-label" %>
         <div class="controls">
         <%= f.select(:tag, ['Personal', 'Tech','News', 'Occupation'],:id=>"multiple",:class=>"select2", :multiple=>"multiple" ,:style=>"width:200px" ) %>
        </div>
      </div>
        
      <%= f.submit "Post", 'class'=>"btn btn-primary"%> 

      <% end %>
    
</div>
<script>
  $('.select2').select2({ placeholder : '' });
</script>

<% if @blogs_all.empty?%>
<%else%>
<div id ="Question">

<div class="span12">  
    <ul class="nav nav-tabs" >
         
          <li  style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Top Blogs', top_blog_blogs_path%></li>
         <li   style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Latest Blogs', latest_blog_blogs_path%></li>
         <li class="active"   style="width: 266px; text-align: center;font-size:15px;"><%= link_to 'My Blogs',  my_blog_blogs_path%></li>  
    </ul>   
</div>

<br><br><br>

    <%@blogs_all.each  do |blog| %>
    <div style =" border:2px solid #e3e3e3;">
            <% user=Profile.find_by_user_id(blog.user_id)%>
            <h4 style = "margin-left:20px;margin-right:20px;"><strong><h4> <%= link_to blog.title, {:controller => "blogs", :action => "view_blog", :id => blog.id }%></h4></strong></h4>
            <div style="float: right;font-size: 9pt;color:#4682B4;margin-right:20px;margin-top:-30px;"><i class="icon-calendar"></i> Posted <%= blog.created_at.to_date.strftime("%B %d, %Y") %></div>
          <% if blog.image_url.nil?%>
          <%else%> 
          <div class="span2">
            <a href="#" class="thumbnail">
            <%= image_tag blog.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:100px;height:50px;" if blog.image?  %>
            </a>
          </div>
        </br></br></br></br>
          <% end%>
        
            <p style = "margin-left:20px;margin-right:20px;font-size:11pt;"><%= blog.content %> </p> 
            <div class= "well" style = "margin-top:20px;margin-left:20px;margin-right:20px;height:20px;">
           <div style = "height:20px;font-size:10px;color:#4682B4;margin-left:-12px;">
                    <% if user.image_url.nil?%>
                        <img src="http://critterapp.pagodabox.com/img/user.jpg" style="margin-right: 10px; width:45px;height:45px;">
                        <% else%> <div style="margin-top:-12px;float:left;">
                          <%= image_tag user.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:45px;height:45px;"%>
                        </div>
                        <% end%><%= link_to "#{user.first_name}", {:controller => "profiles", :action => "about", :id => blog.user_id }%> 
                   | <i class="icon-share"></i> <%= blog.kudos%> Kudos
                   | <i class="icon-tags"></i> Tags : <%= link_to blog.tag, {:controller => "blogs", :action => "list_by_tags", :tag => blog.tag } , :class => "label label-info" %> 
       </div>             
    </div>
    </div></br>     
    <%end%>  

</div>

<% end%>

app/views/blogs/top_blog.html.erb
 
 <link href="/assets/blogs.css" media="screen" rel="stylesheet" type="text/css" />
 <script src="js/jquery-1.9.1.min.js"></script>
 <script src="js/select2.min.js"></script>
 <link rel="stylesheet" type="text/css" href="css/select2.css"/> 
 <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/> 
 <link rel="stylesheet" type="text/css" href="../select2-bootstrap.css"/>

    <div id="form_box">
    <h4 style="margin-left: 200px;">New Blog</h4>

     
      <fieldset style="margin-left: 200px;margin-top: 20px;">  
      <%= form_for :blog, :url => {:controller => 'blogs', :action => 'create'} do |f| %>

      <div class="control-group">
         <%=f.label :blog_header ,:class=>"control-label" %>
         <div class="controls">
         <%=f.text_field :title ,:autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
        </div>
      </div>
      
      <div class="control-group">
         <%=f.label :content , :class=>"control-label"%>
         <div class="controls">
         <%=f.text_area :content, :rows => 4, :cols => 30 ,:id=>"textarea", :class=>"input-xlarge"%>
         </div>
      </div>
      
       
    <div class="control-group">
    <%=f.label :Image , :class=>"control-label"%>
   
              <div class="controls"> 
                <%= f.file_field :image ,:class=>"control-label", :id=>"textinput", :class=>"input-xlarge" %>
              </div>
   
      </div>
      <div class="control-group">
         <%=f.label :tag ,:class=>"control-label" %>
         <div class="controls">
         <%= f.select(:tag, ['Personal', 'Tech','News', 'Occupation'],:id=>"multiple",:class=>"select2", :multiple=>"multiple" ,:style=>"width:200px" ) %>
        </div>
      </div>
        
      <%= f.submit "Post", 'class'=>"btn btn-primary"%> 

      <% end %>
    
</div>
<script>
  $('.select2').select2({ placeholder : '' });
</script>

<% if @blogs_all.empty?%>
<%else%>
<div id ="Question">

<div class="span12">  
    <ul class="nav nav-tabs" >
         
          <li class="active"  style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Top Blogs', top_blog_blogs_path%></li>
         <li   style="width: 267px; text-align: center;font-size:15px;"><%= link_to 'Latest Blogs', latest_blog_blogs_path%></li>
         <li   style="width: 266px; text-align: center;font-size:15px;"><%= link_to 'My Blogs',  my_blog_blogs_path%></li>  
    </ul>   
</div>

<br><br><br>

    <%@blogs_all.each  do |blog| %>
    <div style =" border:2px solid #e3e3e3;">
            <% user=Profile.find_by_user_id(blog.user_id)%>
            <h4 style = "margin-left:20px;margin-right:20px;"><strong><h4> <%= link_to blog.title, {:controller => "blogs", :action => "view_blog", :id => blog.id }%></h4></strong></h4>
            <div style="float: right;font-size: 9pt;color:#4682B4;margin-right:20px;margin-top:-30px;"><i class="icon-calendar"></i> Posted <%= blog.created_at.to_date.strftime("%B %d, %Y") %></div>
          <% if blog.image_url.nil?%>
         
          <%else%> 
          <div class="span2">
            <a href="#" class="thumbnail">
            <%= image_tag blog.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:100px;height:50px;" if blog.image?  %>
            </a>
          </div>
        </br></br></br></br>
          <% end%>
        
            <p style = "margin-left:20px;margin-right:20px;font-size:11pt;"><%= blog.content %> </p> 
            <div class= "well" style = "margin-top:20px;margin-left:20px;margin-right:20px;height:20px;">
          <div style = "height:20px;font-size:10px;color:#4682B4;margin-left:-12px;">
                    <% if user.image_url.nil?%>
                         <img src="http://critterapp.pagodabox.com/img/user.jpg" style="margin-right: 10px; width:45px;height:45px;">
                        <% else%> <div style="margin-top:-12px;float:left;">
                          <%= image_tag user.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:45px;height:45px;"%>
                        </div>
                        <% end%><%= link_to "#{user.first_name}", {:controller => "profiles", :action => "about", :id => blog.user_id }%> 
                   | <i class="icon-share"></i> <%= blog.kudos%> Kudos
                   | <i class="icon-tags"></i> Tags : <%= link_to blog.tag, {:controller => "blogs", :action => "list_by_tags", :tag => blog.tag } , :class => "label label-info" %> 
       </div>             
    </div>
    </div></br>     
    <%end%>  

</div>

<% end%>