config/routes.rb
QLink::Application.routes.draw do

get '/404', to: 'errors#not_found'
get '/500', to: 'errors#server_error'

resources :events do
   member do
   end
   collection do
     post 'save_event'
     get 'index'
     get 'showcalender'
     get 'firstpage'
     get 'invitepeople'
     post 'save_eventemail'
     get 'firstpageremove'
     get 'update_event'
     post 'updatesave_event'
   end
  end
  
resources :profiles do
  member do
  end
  collection do

    get 'profile_form'
    post 'create'
    get 'about'
    get 'events'
    get 'search'
    post 'fill_details'
    post 'add_picture'
    get 'upload_file_for_postmessage'
    get 'photos'
    get 'videos'
    get 'change_profile_pic'  
    post 'save_profile'
    get 'my_posts'
    get 'my_blogs'
    get 'my_discussions'
  end
end
resources :home do
  member do
  end
  collection do
    get 'home'
    post 'create'
    post 'postmessage'
    get 'upload'
    get 'latest_blogs'
    get 'latest_discussions'
    get 'latest_events'
    get 'destroy'
    get 'kudos_to_post'
  end
end

    
match "/contacts/:gmail/callback" => "contacts#contacts_callback"
match "/contacts/failure" => "contacts#failure"
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "sessions"}
root :to => "users#index"
resources :users do
    member do

    end
    collection do
        post 'reset_password'
        get 'welcomepage'  
        get 'skip_import_contacts' 
        get 'skip_add_profile_picture'
        get 'set_password'
        post 'save_password'         
    end
end

resources :discussions do   
  member do
  
  end
  collection do
    get 'view_disc'
   post 'create'
   get 'my_disc'
   get 'top_disc'
   get 'latest_disc'
   get 'add_kudos_discussion'
   get 'list_by_tags'
   get 'destroy'
   get 'kudos_to_discussion'
  end
end

resources :blogs do   
  member do
  
  end
  collection do

    get'add_kudos_blog'
    get 'view_blog'
    post 'create'
    get 'my_blog'
    get 'top_blog'
    get 'latest_blog'
    get 'list_by_tags'
    get 'destroy'
    get 'kudos_to_blog'
  end
end

resources :answers  do
  member do
  end
  collection do
    post 'create_ans'
    get 'add_kudos_answer'
    get 'kudos_to_answer'
  end
end

resources :comments  do
  member do
  end
  collection do
    get 'add_kudos_comments'
    post 'create_comment'
     get 'kudos_to_comment'
  end
end

end

app/models/user.rb
class User < ActiveRecord::Base

  	# Include default devise modules. Others available are:
  	# :token_authenticatable, :confirmable,
  	# :lockable, :timeoutable and :omniauthable

  	devise :database_authenticatable, :registerable, :token_authenticatable,
        :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  	# Setup accessible (or protected) attributes for your model

  	attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :passwordflag,:token,:refresh_token
    
    
    
  	# attr_accessible :title, :body

has_many :post   
has_many :event
has_many :blog
has_many :discussion
has_one :profile



  	def self.find_for_google_oauth2(access_token, signed_in_resource=nil)

		    data = access_token['info']
		    if user = User.where(:email => data['email']).first
			     return user
		    else #create a user with stub pwd
			     User.create!(:email => data['email'], :password => Devise.friendly_token[0,20],  :passwordflag => :false)

		    end
	  end

    def self.create_password(password)
        if password.present?
           encrypted_password = Digest::SHA512.hexdigest(password)
        end
        return encrypted_password
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authorize_user! , :except => [:index]

	def index
		@user = current_user
		if user_signed_in?
			user = User.find(current_user.id)
            if user.passwordflag == false
                sign_in user
                redirect_to :controller=>"users", :action=>"welcomepage" and return
            end

            profile = Profile.find(current_user.id)
            if (profile.first_name.nil?) || (profile.last_name.nil?)
                redirect_to :controller=>"users", :action=>"welcomepage" and return
            end
            if profile.image_url.nil?
                redirect_to :controller=>"users", :action=>"welcomepage" and return
            end
			redirect_to home_home_index_path and return
		end
		render :layout => 'login'	
	end

	def set_password
	end
	def save_password
		@user = current_user
			if(User.create_password(params[:password][:password]) == @user.encrypted_password)
				if(params[:password][:new_password] == params[:password][:Confirm_new_password])
					flash[:notice] = "Password changed"
					@user.update_attribute(:encrypted_password ,User.create_password(params[:password][:new_password]))
					redirect_to set_password_users_path
				else
					flash[:notice] = "Password Confirmation not ok"
					redirect_to set_password_users_path
	            end
	        else
	        	if(params[:password][:password]==""|| params[:password][:new_password]==""||params[:password][:Confirm_new_password]=="")
	         		flash[:notice] = "Filds can't be blank"
			 		redirect_to set_password_users_path
			    else
					flash[:notice] = "Wrong password"
			 		redirect_to set_password_users_path
				end
			end
	end
	

	def welcomepage
		@user = current_user
		if session[:@welcome] == "done"
			redirect_to home_home_index_path and return
		end
		#render :json=>{:data=>session[:@auth]} 
		@user_profile_info = session[:@auth][:info]
		render :layout => 'welcomepage'
	end

	def reset_password
		@user = current_user
		password = params[:user][:password]
		if password.empty?
			flash[:alert] = "Password entered is blank!"
			redirect_to welcomepage_users_path and return
		else
			@user.update_attribute(:encrypted_password ,User.create_password(password))
			if @user.save
				@user.update_attribute(:passwordflag ,true)
				session[:@welcome]="done"
				redirect_to welcomepage_users_path and return
			end
		end	
	end

	def skip_import_contacts
		session[:@welcome] = "password"
		redirect_to welcomepage_users_path and return
	end

	def skip_add_profile_picture
               session[:@welcome] = "contacts"
               redirect_to welcomepage_users_path and return
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def resource_name
   		:user
  	end

 	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
  	def resource_class
  		devise_mapping.to
	end
end

app/views/users/index.html.erb
<link href="/assets/login.css" media="screen" rel="stylesheet" type="text/css" />
<div id="container_for_login">
    <div id="header_for_login">
        <%= image_tag("logo-beta.jpg", :alt => "logo", 'class' => "style_image_for_login") %>
    </div>

    <div id="error_for_login">
        <% if (alert.nil? and notice.nil?)%>

        <% else if alert.nil?%>
            <div class="alert alert-success" style="margin:0px; width:auto;text-align: center;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4 ><%= notice %></h4>
            </div> 
            <% else%>
                <div class="alert alert-error" style="margin:0px; width:auto; text-align: center;">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h4 ><%= alert %></h4>
                </div> 
            <% end%>
        <% end%> 
    </div> 

    <div id="inner_container_for_login">
        <div id="login_form">
            <div id="sign_in">
                <h2>Sign in</h2>
            </div>
            <div id="qlink">
                <i>Q-Link</i>
            </div>
            
            <div id="inner_login_form">
                    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                     Email
                     <%= f.email_field :email, {:class=>"input-xlarge"}%>
                            
                    Password                             
                    <%= f.password_field :password,{:class => "input-xlarge"}%>
            </div>  
                   <div id="login_form_checkbox">       
                        <% if devise_mapping.rememberable? -%>
                            
                                    <%= f.check_box :remember_me %>
                                    <%=f.label :remember_me%>
                               
                        <% end -%>  
                    </div> 
                
                    <div id="btnSign_in">
                    </br>
                        <%= f.submit "Sign in", 'class'=>"btn btn-primary", 'id'=>'submit_button' %>
                
                    </div>

                    <div id="btnGoogle">
                    
                         <%= link_to image_tag("sign-in.png"), user_omniauth_authorize_path(:google_oauth2), :method => "get" %>
                    </div>
                    <% end %>
        
        </div>

           


        <div id="about_for_login">
            <h4> Sign in and start sharing with Q-Link</h4>
            </br>
            <h5>
            <%= image_tag("share_icon.png", :alt => "icon") %>
            &nbsp &nbspShare whats in your mind with Friends
            </h5>
           
            <h5>
            <%= image_tag("blog_icon.png", :alt => "icon") %>
            &nbsp &nbspView and Share your Blogs
            </h5>
            
            <h5>
            <%= image_tag("photo_icon.png", :alt => "icon") %>
            &nbsp &nbspShare photos and videos with Friends
            </h5>

            <h5>
            <%= image_tag("events_icon.png", :alt => "icon") %>
            &nbsp &nbspOrganize and create events
            </h5>

            <h5>
            <%= image_tag("question_icon.png", :alt => "icon") %>
            &nbsp &nbspAsk Questions and take part in Discussions.
            </h5>

        </div>

        
        

    </div>
    
    <div id="footer_for_login">
        <p>Copyright © 2013 Q-Link RoR Team @ QBurst 2013</p>
    </div>
</div>

app/views/users/pageload.html.erb
<!DOCTYPE html>   
<html lang="en">   
<head>   
<meta charset="utf-8">   
<title>Twitter Bootstrap Modals Example</title>   
<meta name="description" content="Creating Modal Window with Twitter Bootstrap">  
<link href="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/css/bootstrap.css" rel="stylesheet">   
</head>  
<body>  
<div class="container">  


<div id="d" class="modal hide fade in" style="display: none; ">  
<div class="modal-header">  
<a class="close" data-dismiss="modal">×</a>  
<h3>Set Your Username and Password</h3>  
</div>  
<div class="modal-body">  
<%= form_for :user, url: { action: 'save_profile', controller: "users", method: :post} do |f| %>
       <p>
        <%=f.label :Username %>
        <%=f.text_field :username %>
        </p>
      	<p>
        <%=f.label :password %>
        <%=f.password_field :password %>
      	</p>
	 	
	<p>
      <%= f.submit(type: 'submit', class: "btn btn-info", :value => "UPDATE")  %>
	</p>
  <% end %>                   
</div>  
</div>



<div id="example" class="modal hide fade in" style="display: none; ">  
<div class="modal-header">  

<h3>Welcome to Q-Link</h3>  
</div>  
<div class="modal-body">  
     
    <p> Qlink's mission is to make the world more open and connected.
                Mission.Qlink's mission is to give people the power to share and make the world more open and connected.
    </p>

</div>  
<div class="modal-footer">  
	
		<a data-toggle="modal" data-dismiss="modal" href="#d" class="btn btn-success" >Continue to Q-Link</a>  

</div>  
</div> 


<p><a data-toggle="modal" href="#example" class="btn btn-primary btn-large">Launch demo modal</a></p>  
</div>  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>  
<script src="/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-modal.js"></script>  
</body>  
</html>  

app/views/users/set_password.html.erb
<html>
<link href="/assets/events.css" media="screen" rel="stylesheet" type="text/css" />
<div id = "outer" style="width:820px;padding-bottom:10px;">
      <div class="span12" style="margin:10px 0px 0px 20px;padding-right:30px;">   
            <ul class="nav nav-tabs">
              <li class= "active" style="width: 395px; text-align: center;"> <%= link_to "Change password", set_password_users_path%></li>
              <li  style="width: 395px; text-align: center;"><%= link_to "Change Picture", change_profile_pic_profiles_path %></li>
   </ul>
 </div>
 <body>
 <div style="margin-left:80px;">
    <h4 style="margin-left: -10px;">Would You like to reset your password ?</h4>
<%= form_for :password, url: { action: 'save_password', controller: "users", method: :post } do |f| %>
      <p style="margin-left: 40px;">
         <%=f.label :old_password %>
         <%=f.text_field :password %>
      </p>
	  <p style="margin-left: 40px;">
         <%=f.label :new_password %>
         <%=f.password_field :new_password%>
	 </p>
    <p style="margin-left: 40px;">
         <%=f.label :Confirm_new_password %>
         <%=f.password_field :Confirm_new_password%>
	 </p>
	<p style="margin-left: 80px;">
      <%= f.submit(type: 'submit', class: "btn btn-info", :value => "Confirm Password")  %>
	</p>
  <% end %>
</div>
</div>
</body>
</html>

app/views/users/set_username.html.erb
<html>  
<div id='forusername'>	
<%= form_for :user, url: { action: 'change_username', controller: "users", method: :post} do |f| %>
      	<p>
        <%=f.label :username %>
        <%=f.text_field :username , :value =>"#{@user.username}"  %>
      	</p>	
	<p>
      <%= f.submit(type: 'submit', class: "btn btn-info", :value => "CHANGE USERNAME")  %>
	</p>
  <% end %>
  </div>

</html>

app/views/users/step_one.html.erb
<html>

<body>
		Introduction page

		Welcome to Qlink
</body>

</html>

app/views/users/test.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="scripts/jquery-1.4.3.min.js" type="text/javascript"></script>
    <style type="text/css">
        .web_dialog_overlay
        {
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            background: #000000;
            opacity: .15;
            filter: alpha(opacity=15);
            -moz-opacity: .15;
            z-index: 101;
            display: none;
        }
        .web_dialog
        {
            display: none;
            position: fixed;
            width:600px;
    		height:400px;
            top:10%;
            left:10%;
            background-color: #ffffff;
            border: 2px solid #336699;
            z-index: 102;
            font-family: Verdana;
            font-size: 10pt;
        }
        .web_dialog_title
        {
            border-bottom: solid 2px #336699;
            background-color: #336699;
            padding: 4px;
            color: White;
            font-weight:bold;
        }
        .web_dialog_title a
        {
            color: White;
            text-decoration: none;
        }
        .align_right
        {
            text-align: right;
        }
    </style>
    <script type="text/javascript">

        $(document).ready(function ()
        {
            
            $("#btnWelcome").click(function (e){
                ShowModal();
                e.preventDefault();
            });

            $("#btnWelcomeClose").click(function (e)
            {
                HideModal();
                e.preventDefault();
            });


            $("#btnShowModal").click(function (e)
            {
                ShowDialog(true);
                e.preventDefault();
            });

            $("#btnShow").click(function (e)
            {
                ShowDialog(false);
                e.preventDefault();
            });

            $("#btnClose").click(function (e)
            {
                HideDialog();
                e.preventDefault();
            });


            $("#btnSetClose").click(function (e)
            {
                HideDialogSetPassword();
                e.preventDefault();
            });


            $("#btnSubmit").click(function (e)
            {
		
                var brand = $("#brands input:radio:checked").val();
                $("#output").html("<b>Your favorite mobile brand: </b>" + brand);
                HideDialog();
                e.preventDefault();
            });
        });

        function ShowModal()
        {

            $("#overlay").show();
            $("#form").fadeIn(300);
            $("#overlay").unbind("click");
        }

        function ShowDialog(modal)
        {
            
            if (modal)
            {
            	$("#overlay").show();
            	$("#dialog").fadeIn(300);
                $("#overlay").unbind("click");
            }
            else
            {
                
                
                    $("#overlay").show();
            		$("#setPassword").fadeIn(300);
                	$("#overlay").unbind("click");
               
            }
        }

        function HideModal()
        {
            $("#overlay").hide();
            $("#form").fadeOut(300);

        }
        function HideDialog()
        {
            $("#overlay").hide();
            $("#dialog").fadeOut(300);
        } 
        

        function HideDialogSetPassword()
        {
            $("#overlay").hide();
            $("#setPassword").fadeOut(300);
        } 
    </script>
</head>
<body>
    
    <h3>Welcome to Q-Link</h3>
    
    
    <input type="button" id="btnShowModal" value="Update Your Profile" class="btn btn-danger" />  
     <input type="button" id="btnShow" value="Set Your Password and Username" class="btn btn-danger" />
 </br>
 <input type="button" id="btnWelcome" value="welcome" class="btn btn-success" />
    
    <div id="output"></div>
    
    <div id="overlay" class="web_dialog_overlay"></div>
    
    <div id="dialog" class="web_dialog">

    	<a href="#" id="btnClose">Close</a>
    		<fieldset style="margin-left:40px;">
        	<%=  form_for :profile, :url => {:controller => 'profiles', :action => 'create'} do |f| %>
                <!-- Text input-->
                <div class="control-group">
                <%= f.label :first_name, :class=>"control-label"%>
                  <div class="controls">
                    <%= f.text_field :first_name, :autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
                  </div>
                </div>

                <!-- Text input-->
                <div class="control-group">
                    <%= f.label :last_name, :class=>"control-label"%>
                    <div class="controls">
                      <%= f.text_field :last_name , :autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
                    </div>
                </div>

                <div class="control-group">
                    <%= f.label :date_of_birth, :class=>"control-label"%>
                    <div class="controls">
                      <%= f.text_field :date_of_birth, 'data-behaviour' => 'datepicker' %>
                    </div>
                </div>
            
                <!-- Textarea -->
                <div class="control-group">
                    <%= f.label :address, :class=>"control-label"%>
                    <div class="controls">                     
                      <%= f.text_area :place, :style=>"height: 30px;", :id=>"textarea" %>
                    </div>
                </div>
                    <p>
    <%= f.file_field :image %>
  </p>
                <%= f.submit "Update", :id=>"submit", :class=>"btn btn-primary", 'data-loading-text'=>"Updating..."%>
          <% end %>
          </fieldset>
    </div>

    <div id="setPassword" class="web_dialog">
    	<a href="#" id="btnSetClose">Close</a>
    	<fieldset style="margin-left:40px;">
    	<%= form_for :user, url: { action: 'save_profile', controller: "users", method: :post} do |f| %>
       <p>
        <%=f.label :Username %>
        <%=f.text_field :username %>
        </p>
      	<p>
        <%=f.label :password %>
        <%=f.password_field :password %>
      	</p>
	 	
	<p>
      <%= f.submit(type: 'submit', class: "btn btn-info", :value => "UPDATE")  %>
	</p>
  <% end %>
  </fieldset>
    </div>
    






    <div id="form" class="web_dialog">

        <a href="#" id="btnWelcomeClose">Close</a>
            <fieldset style="margin-left:40px;">
            <%=  form_for :profile, :url => {:controller => 'profiles', :action => 'create'} do |f| %>
                <!-- Text input-->
                <div class="control-group">
                <%= f.label :first_name, :class=>"control-label"%>
                  <div class="controls">
                    <%= f.text_field :first_name, :autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
                  </div>
                </div>

                <!-- Text input-->
                <div class="control-group">
                    <%= f.label :last_name, :class=>"control-label"%>
                    <div class="controls">
                      <%= f.text_field :last_name , :autofocus => true, :id=>"textinput", :class=>"input-xlarge" %>
                    </div>
                </div>

                <div class="control-group">
                    <%= f.label :date_of_birth, :class=>"control-label"%>
                    <div class="controls">
                      <%= f.text_field :date_of_birth, 'data-behaviour' => 'datepicker' %>
                    </div>
                </div>
            
                <!-- Textarea -->
                <div class="control-group">
                    <%= f.label :address, :class=>"control-label"%>
                    <div class="controls">                     
                      <%= f.text_area :place, :style=>"height: 30px;", :id=>"textarea" %>
                    </div>
                </div>
                    <p>
    <%= f.file_field :image %>
  </p>
                <%= f.submit "Update", :id=>"submit", :class=>"btn btn-primary", 'data-loading-text'=>"Updating..."%>
          <% end %>
          </fieldset>
    </div>
</body>
</html>

app/views/users/welcomepage.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    
</head>
<body>
    
</body>
</html>