config/routes.rb
QLink::Application.routes.draw do

get '/404', to: 'errors#not_found'
get '/500', to: 'errors#server_error'

resources :events do
   member do
   end
   collection do
     post 'save_event'
     get 'index'
     get 'showcalender'
     get 'firstpage'
     get 'invitepeople'
     post 'save_eventemail'
     get 'firstpageremove'
     get 'update_event'
     post 'updatesave_event'
   end
  end
  
resources :profiles do
  member do
  end
  collection do

    get 'profile_form'
    post 'create'
    get 'about'
    get 'events'
    get 'search'
    post 'fill_details'
    post 'add_picture'
    get 'upload_file_for_postmessage'
    get 'photos'
    get 'videos'
    get 'change_profile_pic'  
    post 'save_profile'
    get 'my_posts'
    get 'my_blogs'
    get 'my_discussions'
  end
end
resources :home do
  member do
  end
  collection do
    get 'home'
    post 'create'
    post 'postmessage'
    get 'upload'
    get 'latest_blogs'
    get 'latest_discussions'
    get 'latest_events'
    get 'destroy'
    get 'kudos_to_post'
  end
end

    
match "/contacts/:gmail/callback" => "contacts#contacts_callback"
match "/contacts/failure" => "contacts#failure"
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "sessions"}
root :to => "users#index"
resources :users do
    member do

    end
    collection do
        post 'reset_password'
        get 'welcomepage'  
        get 'skip_import_contacts' 
        get 'skip_add_profile_picture'
        get 'set_password'
        post 'save_password'         
    end
end

resources :discussions do   
  member do
  
  end
  collection do
    get 'view_disc'
   post 'create'
   get 'my_disc'
   get 'top_disc'
   get 'latest_disc'
   get 'add_kudos_discussion'
   get 'list_by_tags'
   get 'destroy'
   get 'kudos_to_discussion'
  end
end

resources :blogs do   
  member do
  
  end
  collection do

    get'add_kudos_blog'
    get 'view_blog'
    post 'create'
    get 'my_blog'
    get 'top_blog'
    get 'latest_blog'
    get 'list_by_tags'
    get 'destroy'
    get 'kudos_to_blog'
  end
end

resources :answers  do
  member do
  end
  collection do
    post 'create_ans'
    get 'add_kudos_answer'
    get 'kudos_to_answer'
  end
end

resources :comments  do
  member do
  end
  collection do
    get 'add_kudos_comments'
    post 'create_comment'
     get 'kudos_to_comment'
  end
end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :discussion_id ,:user_id

  has_one :user
  belongs_to :discussion

end

app/models/blog.rb
class Blog < ActiveRecord::Base



  attr_accessible :content, :tag, :title, :user_id, :image, :remote_image_url
  validates_presence_of :title
  has_one :user
  mount_uploader :image, ImageUploader
  has_many :comments

end

app/models/blog_tags.rb
class BlogTags < ActiveRecord::Base
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 attr_accessible :content, :blog_id ,:user_id

  has_one :user
  belongs_to :blog
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name, :user_id
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  attr_accessible :content, :title, :tag, :user_id
  has_one :user
  has_many :answers

end

app/models/event.rb
class Event < ActiveRecord::Base



  attr_accessible :allday, :description, :endtime, :start, :title, :user_id,:eventId,:flag

  validates_presence_of :title
  validate :validate_end_date_before_start_date
  has_one :user
  
  def validate_end_date_before_start_date
    if endtime && start && endtime < start
      errors.add(:endtime,"")
    end
  end


end

app/models/eventemail.rb
class Eventemail < ActiveRecord::Base
  attr_accessible :email, :event_id
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i,:message => "invalid email"
end

app/models/kudos_to_blog.rb
class KudosToBlog < ActiveRecord::Base
   attr_accessible :user_id,:blog_id
end

app/models/kudos_to_posts.rb
class KudosToPosts < ActiveRecord::Base
  attr_accessible :kudos, :user_id, :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :description, :user_id, :image, :receiver_id, :video, :kudos
  has_one :user
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  attr_accessible :date_of_birth, :first_name, :last_name, :place, :user_id, :image, :gender
  has_one :user
   mount_uploader :image, ImageUploader

 validates_presence_of :date_of_birth, :first_name, :last_name, :place, :gender

 # searchable do
 #    text :first_name, :last_name
 #  end
end

app/models/user.rb
class User < ActiveRecord::Base

  	# Include default devise modules. Others available are:
  	# :token_authenticatable, :confirmable,
  	# :lockable, :timeoutable and :omniauthable

  	devise :database_authenticatable, :registerable, :token_authenticatable,
        :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  	# Setup accessible (or protected) attributes for your model

  	attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :passwordflag,:token,:refresh_token
    
    
    
  	# attr_accessible :title, :body

has_many :post   
has_many :event
has_many :blog
has_many :discussion
has_one :profile



  	def self.find_for_google_oauth2(access_token, signed_in_resource=nil)

		    data = access_token['info']
		    if user = User.where(:email => data['email']).first
			     return user
		    else #create a user with stub pwd
			     User.create!(:email => data['email'], :password => Devise.friendly_token[0,20],  :passwordflag => :false)

		    end
	  end

    def self.create_password(password)
        if password.present?
           encrypted_password = Digest::SHA512.hexdigest(password)
        end
        return encrypted_password
    end
end

app/models/userevent.rb
class Userevent < ActiveRecord::Base

  attr_accessible :description, :endtime, :start, :title, :user_id, :eventid

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def resource_name
   		:user
  	end

 	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
  	def resource_class
  		devise_mapping.to
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



<head>
  <title>QLink</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-fluid">  
        <div class="row-fluid" >
      		<div class="well sidebar-nav" style="height: 80px;padding-left: 10px; padding-bottom: 10px; padding-top: 10px;background:transparent;border:none">
            <div class="pull-left" style="width: 140px;height: 60px;margin-top:10px;margin-left:20px;">
      			  <%=link_to image_tag("logo-beta.jpg"),{:controller=>"home", :action=>"home"}%> 	
              </div>	    
              <div class="pull-right" style="margin-top:25px;">
                  <% profile=Profile.find_by_user_id(current_user.id)%>
                  <% if profile.image_url.nil?%>
                      <img src="http://critterapp.pagodabox.com/img/user.jpg" alt="" style="margin-right: 10px; width:30px;height:30px;-webkit-border-radius: 30px;-moz-border-radius: 30px;border-radius: 30px;border:2px solid #fff;">
                  <% else%>
                      <%= image_tag profile.image_url(:thumb).to_s, :style=>"margin-right: 10px; width:30px;height:30px;-webkit-border-radius: 30px;-moz-border-radius: 30px;
                        border-radius: 30px;border:2px solid #fff;"%>
                  <% end%>

                  <ul class="nav pull-right" style="margin-top: -25px;">

                  <% user=Profile.find_by_user_id(current_user.id)%>
                  <%if ((user.first_name.nil?)||(user.first_name==""))%>
                      <li id="drop_down" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:white;background-color:#3b5998;">Welcome User<b class="caret"></b></a>
                  <%else%>
                      <li id="drop_down" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:white;background-color:#3b5998;"><%=user.first_name%>&nbsp<%=user.last_name%> <b class="caret"></b></a>
                  <% end%>
                        <ul id="drop_down_toggle" class="dropdown-menu">                           

                            <li>
                              <div>
                                <i class="icon-wrench" style="margin:0 5px 0 10px;"></i><%= link_to 'Settings', set_password_users_path, :style=>"padding-right:30px; text-decoration:none;"%>
                              </div>
                            </li>
                            <li class="divider"></li>
                            
                            <li>
                              <div>
                                <i class="icon-off" style="margin:0 5px 0 10px;"></i><%= link_to 'Logout', destroy_user_session_path, :method=>:delete, :style=>"padding-right:30px; text-decoration:none;" %>
                              <div>
                            </li>
                        </ul>
                    </li>
                </ul>          
              </div>
              <div class="pull-left" style="height:40px;width:270px;margin-left:490px;margin-top:20px;background:white;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;">
                 <%=  form_tag  search_profiles_path, :method=>:get do %> 
                 <p style="height=30px;size=39px; maxlength=255px;padding-top:5px;"> 
                  <%= text_field_tag :search, params[:search], :placeholder=>"Find Other QB's", :style=>"border:none;background-color:white;" %>
                  <button type="submit" class="btn btn-primary" style="margin-top:-10px;background:#3b5998;"> <i class="icon-search icon-white" ></i></button></p>
                  <% end%>
              </div>
         	</div>
		    </div>

        <% if (alert.nil? and notice.nil?)%>
        <% else if alert.nil?%>
          <div class="alert alert-success" style="text-align: center;">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <p ><%= notice %></p>
          </div> 
          <% else%>
              <div class="alert alert-error" style="text-align: center;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <p ><%= alert %></p>
            </div> 
          <% end%>
        <% end%>    
                  

      <div class="row-fluid" > 
        <div class="span2" >  
          <div class="well sidebar-nav" >
            <ul class="nav nav-list" style="margin-left:20px;">                

              <li><%= link_to 'Home', home_home_index_path%></li></br>
              <li><%= link_to 'Profile', about_profiles_path%></li>  </br>
              <li><%= link_to 'Blogs', top_blog_blogs_path%></li>  </br>
              <li><%= link_to 'Discussions', top_disc_discussions_path%></li>  </br>
              <li><%= link_to 'Events', firstpage_events_path%></li>  </br>      
           </ul>  
          </div> 
        </div>     
        		<%= yield %>			
          <div class="span3" style="float: right; margin-left: 10px;width:200px;"> 
              <div class="well sidebar-nav" style="height:230px;">  
                  <div style="background:white;">
                    <%= image_tag("Chat.Icon.JPG", :alt => "icon", :style=>"margin-left:10px;height:50px;width:50px;")%>
                    <h5 style="float:right;margin-right:20px;margin-top:15px;color:#4682B4;">Chat List</h5>
                  </div>
              </div>
          </div>
      </div>
    </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Qlinkdemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/welcomepage.html.erb
<!-- layout for first time users as welcome page -->
<!DOCTYPE html>
<html>

<head>
  <title>Qlinkdemo</title>
  <link href="/assets/welcomepage.css" media="screen" rel="stylesheet" type="text/css" />
 <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!-- script for calling modal -->
  <script type="text/javascript">

        $(document).ready(function ()
        {
            <% if session[:@welcome] == "show"%>
                $("#overlay").show();
                $("#fill_details").fadeIn(300);
                $("#overlay").unbind("click");
            <% end %>

            <% if session[:@welcome] == "password"%>
                $("#overlay").show();
                $("#set_password").fadeToggle(1000);
                $("#overlay").unbind("click");
            <% end %>   

            <% if session[:@welcome] == "avatar"%>
                $("#overlay").show();
                $("#add_picture").fadeToggle(1000);
                $("#overlay").unbind("click");
            <% end %>   

            <% if session[:@welcome] == "contacts"%>
                $("#overlay").show();
                $("#import_contacts").fadeToggle(1000);
                $("#overlay").unbind("click");
            <% end %>      
        });

         
    </script>
</head>
<body>
    <div id="container_for_welcome">
        <div id="header_for_welcome">
            <%= image_tag("logo (2).jpg", :alt => "logo", 'class' => "style_image_for_welcome") %>
            <div class="pull-right">
                <ul class="nav pull-right" style="padding-top: 15px;">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: black;"><b>Signed in as <%=@user.email%></b><b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">                           
                            <li>
                                <div><i class="icon-off"></i><%= link_to 'Logout', destroy_user_session_path, :method=>:delete, :style=>"padding-right:30px; text-decoration:none;" %>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div> 
        </div>

        <% if (alert.nil? and notice.nil?)%>


<!-- for showing alert as errors and success -->
        <% else if alert.nil?%>
            <div class="alert alert-success" style="text-align: center;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4><%= notice %></h4>
            </div> 
            <% else%>
                <div class="alert alert-error" style="text-align: center;">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h4><%= alert %></h4>
                </div> 
            <% end%>
        <% end%>
        <%= yield %> 
        
    </div>

    <div id="overlay" class="web_dialog_overlay">
        
    </div>


  <!-- modal div for first time users to fill user profile -->

    <div id="fill_details" class="web_dialog">
        <h3>Tell us about yourself</h3>
        <%=  form_for :profile, :url => {:controller => 'profiles', :action => 'fill_details'} do |f| %>
                <!-- Text input-->
            <fieldset style="margin-left:40px;">
                
                    <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>First Name</b></p>
                    <div class="controls">
                        <%= f.text_field :first_name, :autofocus => true, :id=>"textinput", :value => "#{@user_profile_info.first_name}", :class=>"input-large" %>
                    </div>
                
                <!-- Text input-->
                <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>Last Name</b></p>
                    <div class="controls">
                        <%= f.text_field :last_name , :autofocus => true, :id=>"textinput", :value => "#{@user_profile_info.last_name}", :class=>"input-large" %>
                    </div>
                

                <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>Date Of Birth</b></p>
                    <div class="controls">
                        <%= f.text_field :date_of_birth, 'data-behaviour' => 'datepicker' %>
                    </div>
                
                <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>Gender</b></p>
                    <div class="controls">
                        <%= f.select :gender, [['Male','male'],['Female','female']] %> 
                    </div>
                
                <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>Location</b></p>
                    <div class="controls">                     
                        <%= f.text_field :place, :autofocus => true, :id=>"textinput", :class=>"input-large" %>
                    </div>
                
                 
                <%= f.submit "Update", :id=>"submit", :class=>"btn btn-success", 'data-loading-text'=>"Updating..."%>
            </fieldset>
        <% end %>
    </div>



    <!-- modal div for first time users to add profile picture -->
    <div id="add_picture" class="web_dialog">
        <h3>Add a Profile Picture </h3>
        <%=  form_for :profile, :url => {:controller => 'profiles', :action => 'add_picture'} do |f| %>
                <!-- Text input-->
            <fieldset style="margin-left:40px;">
                <p>
                    <%= f.file_field :image %>
                </p>
                    
                <%= f.submit "Update", :id=>"submit", :class=>"btn btn-success", 'data-loading-text'=>"Updating...", :style=>"margin-left: 0px;"%>
            </fieldset>
        <% end %> 
        <div id="btnSkip">
            <%= button_to "Skip for now",skip_add_profile_picture_users_path, :method => "get", 'class'=>"btn btn-danger" %>
        </div>  
    </div>



<!-- modal div for first time users to set user password -->
    <div id="set_password" class="web_dialog">
        <h3> Reset password for your Q-Link account </h3>
        <%=  form_for :user, :url => {:controller => 'users', :action => 'reset_password'} do |f| %>
                <!-- Text input-->
            <fieldset style="margin-left:40px;">
                <p style="fontfont-family:'Arial Black', Gadget, sans-serif;
                    font-size: 18px;color:white;"><b>Reset Password</b></p>
                    <div class="controls">
                        <%= f.password_field :password , :autofocus => true, :id=>"textinput", :class=>"input-large" %>
                    </div>
                
                <%= f.submit "RESET", :id=>"submit", :class=>"btn btn-success", :style=>"margin-left:0px;"%>
            </fieldset>
        <% end %> 
    </div>


<!-- modal div for first time users to import contacts-->
    <div id="import_contacts" class="web_dialog" style="text-align:center;">
        <h3 >You can import your contacts from your account</h3>
        <div id="btnImport">
            <%= button_to "Import Contacts", "/contacts/gmail", :method => "get", 'class'=>"btn btn-success" %>
        </div>
        <div id="btnSkip">
            <%= button_to "Skip for now",skip_import_contacts_users_path, :method => "get", 'class'=>"btn btn-danger" %>
        </div>
    </div>
</body>
</html>